Repository woowa-techcamp-2020/bmart-3, pull requests merged in 2020-08, with the labels that each got.

#4 feat: 라우터 적용 및 제품 페이지 렌더링
  client/jsconfig.json
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/App.scss
  client/src/banner/pizza.png
  client/src/component/Cart.js
  client/src/component/Category.js
  client/src/component/Mainpage.js
  client/src/component/mainpage/Banner.js
  client/src/component/mainpage/Category.js
  client/src/component/share/Header.js
  client/src/component/share/Product.js
  client/src/component/share/Product.scss
  client/src/component/share/ScrollTab.js
  client/src/component/share/ScrollTab.scss
  client/src/index.css
  client/src/index.js
Labels: css, enhancement, frontend, markup

#9 Feature/front carousel view
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/App.scss
  client/src/component/Mainpage.js
  client/src/component/mainpage/Banner.js
  client/src/component/mainpage/Category.js
  client/src/component/share/Header.js
  client/src/component/share/ProductItem.js
  client/src/component/share/theme.js
  client/src/index.js
Labels: css, enhancement, feature, frontend, markup

#16 Feature/crawling
  client/package-lock.json
  client/package.json
  crawling/crwaling.py
Labels: backend, db

#15 Feature/front recommend product
  client/package-lock.json
  client/package.json
  client/src/banner/bread.png
  client/src/banner/pizza.png
  client/src/component/Mainpage.js
  client/src/component/example.js
  client/src/component/mainpage/Banner.js
  client/src/component/mainpage/Recommend.js
  client/src/component/share/Product.js
  client/src/component/share/theme.js
Labels: css, feature, frontend, markup

#11 Feature/back graphql
  .gitignore
  server/.babelrc
  server/app.js
  server/bin/www
  server/db/graphql/index.js
  server/db/graphql/resolvers.js
  server/db/graphql/typeDefs.js
  server/db/query/user.js
  server/db/share/connection.js
  server/db/share/db.config.js
  server/db/share/execute-query.js
  server/db/share/ssh.js
  server/db/user.js
  server/package-lock.json
  server/package.json
  server/route/index.js
  server/route/users.js
Labels: api, backend

#21 [Feature/FE] 카테고리 state에 context api 적용 및 s3 이미지 경로 수정
  client/src/component/Mainpage.js
  client/src/component/mainpage/Banner.js
  client/src/component/mainpage/Category.js
  client/src/component/mainpage/PreparedProduct.js
  client/src/component/mainpage/Recommend.js
  client/src/component/mainpage/RecommendStyle.js
  client/src/component/share/Header.js
  client/src/component/share/Product.js
  client/src/component/share/ProductItem.js
  client/src/component/share/ScrollTab.js
  client/src/component/share/constant.js
  client/src/component/share/theme.js
  client/src/component/share/util.js
  client/src/context/CategoryContext.js
Labels: css, enhancement, feature, frontend

#23 Feature/apollo graphql
  client/package-lock.json
  client/package.json
  client/src/component/mainpage/Banner.js
  client/src/component/mainpage/Category.js
  client/src/component/share/ProductItem.js
  client/src/component/share/constant.js
  client/src/context/CategoryContext.js
  client/src/graphql/category.js
  client/src/graphql/product.js
  client/src/index.js
  server/app.js
  server/db/category.js
  server/db/graphql/resolvers.js
  server/db/graphql/typeDefs.js
  server/db/product.js
  server/db/query/category.js
  server/db/query/product.js
  server/db/share/connection.js
  server/db/share/execute-query.js
  server/db/share/ssh.js
  server/package-lock.json
  server/package.json
  server/route/index.js
  server/route/product.js
  server/route/users.js
Labels: api, backend, frontend

#25 feat: tab scroll state에 context api 적용
  client/src/component/Mainpage.js
  client/src/component/share/EventScrollTab.js
  client/src/component/share/ProductScrollTab.js
  client/src/context/CategoryContext.js
  client/src/context/EventScrollContext.js
  client/src/image/egg﹒test.png
Labels: enhancement, frontend

#27 feat: 메인페이지 부모 카테고리별 제품리스트 (10개) 렌더링 구현
  client/src/App.js
  client/src/component/Mainpage.js
  client/src/component/mainpage/Category.js
  client/src/component/mainpage/MapProductList.js
  client/src/component/mainpage/Recommend.js
  client/src/component/share/EventScrollTab.js
  client/src/component/share/Product.js
  client/src/component/share/ProductItem.js
  client/src/context/CategoryContext.js
  client/src/context/EventScrollContext.js
  client/src/context/FetchingContext.js
  client/src/context/ProductContext.js
  client/src/context/RecommendContext.js
  server/db/query/product.js
  server/db/share/db.config.js
Labels: api, backend, db, feature, frontend

#29 Feature/category page
  client/package-lock.json
  client/src/App.js
  client/src/component/ParentCategory.js
  client/src/component/mainpage/Category.js
  client/src/component/share/Advertise.js
  client/src/component/share/Product.js
  client/src/component/share/ProductItem.js
  client/src/component/share/ProductList.js
  client/src/graphql/category.js
  server/db/category.js
  server/db/graphql/resolvers.js
  server/db/graphql/typeDefs.js
  server/db/query/category.js
Labels: css, feature, frontend

#30 [FE/Main page] refactor: mainpage infinite scroll 수정
  client/.babelrc
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/component/Mainpage.js
  client/src/component/ParentCategory.js
  client/src/component/mainpage/MapProductList.js
  client/src/component/share/EventScrollTab.js
  client/src/component/share/Product.js
  client/src/component/share/ProductItem.js
  client/src/component/share/ProductList.js
  client/src/context/CategoryContext.js
  client/src/context/EventScrollContext.js
  client/src/context/FetchingContext.js
  client/src/context/ProductContext.js
  server/db/share/db.config.js
Labels: enhancement, feature, frontend

#34 Feature/docker
  docker/deploy/private/.sample.env
  docker/deploy/private/docker-compose.yml
  docker/deploy/private/start.sh
  docker/deploy/public/.sample.env
  docker/deploy/public/docker-compose.yml
  docker/deploy/public/start.sh
  docker/development/.sample.env
  docker/development/docker-compose.yml
  docker/development/start.sh
  docker/development/stop.sh
  docker/mysql/1-insert-category.sql
  docker/mysql/2-insert-product.sql
  docker/mysql/init/create-table.sql
  docker/nginx/nginx.conf
  server/Dockerfile
  server/app.js
  server/db/share/db.config.js
  server/db/share/execute-query.js
  server/db/user.js
  server/package-lock.json
  server/package.json
  server/sample.env
Labels: backend, db, frontend

#35 feat: 랜덤으로 아이템 가져오는 쿼리 작성
  client/src/component/mainpage/MapProductList.js
  client/src/component/mainpage/ProductForYou.js
  client/src/component/mainpage/Recommend.js
  server/db/graphql/resolvers.js
  server/db/graphql/typeDefs.js
  server/db/product.js
  server/db/query/product.js
Labels: api, backend, feature, frontend

#37 Feature/category detail page
  client/src/App.js
  client/src/component/ChildCategory.js
  client/src/component/ParentCategory.js
  client/src/component/mainpage/Category.js
  client/src/graphql/product.js
  server/db/graphql/resolvers.js
  server/db/graphql/typeDefs.js
  server/db/product.js
  server/db/query/product.js
Labels: api, backend, feature, frontend

#38 Feature/front recommend component
  client/src/component/mainpage/MapProductList.js
  client/src/component/mainpage/ProductForYou.js
  client/src/component/mainpage/Recommend.js
  client/src/component/share/ProductItem.js
  client/src/context/ProductContext.js
  client/src/context/RecommendContext.js
  client/src/graphql/product.js
  docker/mysql/3-반짝할인.sql
  server/db/graphql/resolvers.js
  server/db/graphql/typeDefs.js
  server/db/product.js
  server/db/query/product.js
Labels: api, backend, enhancement, feature, frontend

#40 fix: mysql connection pool 싱글톤으로 바꿈
  server/db/share/connection.js
  server/db/share/execute-query.js
Labels: backend, bug

#41 Feature/front like
  client/src/component/mainpage/NewRelease.js
  client/src/component/mainpage/Recommend.js
  client/src/component/share/ProductItem.js
  client/src/graphql/product.js
  docker/mysql/4-찜하기.sql
  server/db/graphql/resolvers.js
  server/db/graphql/typeDefs.js
  server/db/product.js
  server/db/query/product.js
Labels: api, backend, feature, frontend

#43 Feature/google login
  client/package-lock.json
  client/package.json
  client/sample.env
  client/src/App.js
  client/src/component/Loginpage.js
  client/src/component/Mainpage.js
  client/src/component/mainpage/Category.js
  client/src/component/mainpage/MapProductList.js
  client/src/context/AuthContext.js
  client/src/context/CategoryContext.js
  client/src/context/ProductContext.js
  client/src/graphql/auth.js
  client/src/index.js
  docker/deploy/public/.sample.env
  docker/deploy/public/docker-compose.yml
  docker/development/.sample.env
  docker/development/docker-compose.yml
  docker/nginx/nginx.conf
  server/app.js
  server/config/passport.js
  server/db/authGraphql/authResolvers.js
  server/db/authGraphql/authTypeDefs.js
  server/db/authGraphql/index.js
  server/db/graphql/resolvers.js
  server/db/graphql/typeDefs.js
  server/db/query/user.js
  server/db/user.js
  server/package-lock.json
  server/package.json
Labels: api, backend, frontend

#45 Feature/product order
  client/src/component/ChildCategory.js
  client/src/component/ParentCategory.js
  client/src/component/share/OrderSelector.js
  client/src/graphql/product.js
  docker/mysql/4-liked.sql
  server/db/graphql/resolvers.js
  server/db/graphql/typeDefs.js
  server/db/product.js
  server/db/query/product.js
Labels: api, backend, bug, db, feature, frontend

#48 Fix/merge product order
  server/db/product.js
  server/db/query/product.js
Labels: api, backend, bug

#47 Feature/front product scroll tab
  client/src/component/Mainpage.js
  client/src/component/mainpage/EventArea.js
  client/src/component/mainpage/NewRelease.js
  client/src/component/mainpage/PopularItems.js
  client/src/component/mainpage/ProductForYou.js
  client/src/component/mainpage/Recommend.js
  client/src/component/mainpage/RecommendStyle.js
  client/src/component/mainpage/WhatToEat.js
  client/src/component/share/EventScrollTab.js
  client/src/component/share/Header.js
  client/src/component/share/Product.js
  client/src/component/share/ProductItem.js
  client/src/component/share/ProductScrollTab.js
  client/src/component/share/ShareStyle.js
  client/src/component/share/util.js
  client/src/context/EventScrollContext.js
  client/src/context/ProductContext.js
  client/src/context/ProductScrollContext.js
Labels: enhancement, feature

#49 useQuery -> useLazyQuery 수정, 로그인 로직 수정
  client/src/App.js
  client/src/component/LoginCheck.js
  client/src/component/Loginpage.js
  client/src/component/Mainpage.js
  client/src/component/TotalMenupage.js
  client/src/component/mainpage/Category.js
  client/src/component/mainpage/MapProductList.js
  client/src/component/mainpage/Recommend.js
  client/src/component/share/Header.js
  client/src/context/RecommendContext.js
  client/src/index.js
  docker/deploy/public/start.sh
  docker/development/start.sh
  docker/mysql/4-liked.sql
  server/db/user.js
Labels: frontend

#52 Feature/page link
  client/src/component/share/Product.js
Labels: feature, frontend

#53 fix: 로그인 로직 수정, 로그아웃 버튼 제작
  client/src/App.js
  client/src/component/LoginCheck.js
  client/src/component/Loginpage.js
  client/src/component/share/Header.js
Labels: bug, frontend

#55 Feature/search
  client/src/App.js
  client/src/component/SearchPage.js
  client/src/component/share/Header.js
  client/src/graphql/product.js
  server/app.js
  server/db/graphql/resolvers.js
  server/db/graphql/typeDefs.js
  server/db/product.js
  server/db/query/product.js
  server/service/product.js
Labels: api, backend, feature, frontend

#58 Feature/search result page
  client/src/component/SearchPage.js
Labels: feature, frontend

#56 Feature/front cart
  client/src/App.js
  client/src/component/Cart.js
  client/src/component/LoginCheck.js
  client/src/component/Mainpage.js
  client/src/component/cartpage/CartPage.js
  client/src/component/mainpage/MapProductList.js
  client/src/component/mainpage/RecommendStyle.js
  client/src/component/share/BuyProduct.js
  client/src/component/share/Header.js
  client/src/component/share/Product.js
  client/src/component/share/ProductItem.js
  client/src/component/share/ShareStyle.js
  client/src/component/share/theme.js
  client/src/context/ToggleProductBuyContext.js
Labels: feature, frontend

#59 Feature/front cart
  client/src/component/cartpage/CartPage.js
  client/src/component/share/BuyProduct.js
  client/src/component/share/ProductItem.js
  client/src/context/ToggleProductBuyContext.js
Labels: feature, frontend

#60 Feature/total menu
  client/src/App.js
  client/src/component/TotalMenupage.js
  client/src/component/total-menupage/CategoryList.js
  client/src/component/total-menupage/TotalMenupageStyle.js
  client/src/component/total-menupage/index.js
  client/src/context/CategoryContext.js
  client/src/graphql/category.js
  server/db/graphql/resolvers.js
  server/db/graphql/typeDefs.js
Labels: frontend

#61 Feature/front cart
  client/src/App.js
  client/src/component/cartpage/CartPage.js
  client/src/component/detailpage/ChildCategory.js
  client/src/component/detailpage/ParentCategory.js
  client/src/component/loginpage/LoginCheck.js
  client/src/component/searchpage/SearchPage.js
  client/src/component/share/Header.js
Labels: feature, frontend

#62 Feature/more products
  client/src/App.js
  client/src/component/eventpage/EventPage.js
  client/src/component/mainpage/NewRelease.js
  client/src/component/mainpage/PopularItems.js
  client/src/component/mainpage/ProductForYou.js
  client/src/component/mainpage/Recommend.js
  client/src/component/mainpage/WhatToEat.js
  client/src/component/searchpage/SearchPage.js
  client/src/component/share/ProductList.js
Labels: feature, frontend

#64 feat: 장바구니에 상품 넣기, 장바구니 상품 조회하기 기능 추가
  client/src/component/cartpage/CartPage.js
  client/src/component/share/BuyProduct.js
  client/src/context/ToggleProductBuyContext.js
  client/src/graphql/cart.js
  server/db/cart.js
  server/db/graphql/resolvers.js
  server/db/graphql/typeDefs.js
  server/db/query/cart.js
Labels: api, backend, frontend

#66 fix: 장바구니 담기, 삭제하기, 업데이트하기 로직 문제해결
  client/src/component/cartpage/CartPage.js
  client/src/context/ToggleProductBuyContext.js
Labels: bug, frontend

#67 장바구니 UI 수정
  client/src/component/cartpage/CartPage.js
Labels: enhancement, frontend

#68 fix : 이전검색결과가 남아있던 버그 수정, 불필요한 주석 제거
  client/src/component/eventpage/EventPage.js
  client/src/component/searchpage/SearchPage.js
Labels: bug, frontend

#70 feat: orderlist를 반환하는 백엔드 구현
  client/src/graphql/orderlist.js
  server/db/graphql/resolvers.js
  server/db/graphql/typeDefs.js
  server/db/orderlist.js
  server/db/query/orderlist.js
Labels: api, backend

#69 feat: 주문하기 로직 작성
  client/src/component/cartpage/CartPage.js
  client/src/component/loginpage/LoginCheck.js
  client/src/context/ToggleProductBuyContext.js
  client/src/graphql/cart.js
  server/db/cart.js
  server/db/graphql/resolvers.js
  server/db/graphql/typeDefs.js
  server/db/query/cart.js
Labels: api, backend, frontend
